# Generated by Django 2.0 on 2019-11-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20191130_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
