# Generated by Django 2.0 on 2019-12-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20191207_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='CV',
        ),
    ]
