# Generated by Django 2.0 on 2019-12-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20191207_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='about_you',
            field=models.TextField(blank=True),
        ),
    ]
