# Generated by Django 2.0 on 2019-12-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_applyjob_about_you'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='about_you',
        ),
    ]
